import vrplib
import os
import pandas as pd
import random
import numpy as np

class Instance_generator ():
    """
    Given a directory with n subsets, generate an iterator that gives the next random .vrp instance from any subset.
    
    Directory structure must be:
        Main Directory -> Set directory -> Instances or Instances and Solutions.

    :param directory: The main directory.
    :param bounds: A two tuple with the inferior and superior instance sizes permitted, respectively.
    :param reset: If true, resets the generator with all the instances when finished.
    :param has_solution: If true, every subset must have a .vrp with an equivalent .sol, else, every subset must consist of only .vrp files.
    """
    def __init__(self, directory, bounds=(0,101), reset=False, has_solution=True):
        self.dir = directory
        self.bounds = bounds
        self.instance_sets = os.listdir(directory)
        self.idx = -1
        self.reset = reset
        self.has_solution = has_solution

        current_set = [os.path.join(self.dir, inst_set) for inst_set in self.instance_sets]

        self.files = pd.concat(pd.Series(os.path.join(inst_set, inst) for inst in os.listdir(inst_set)) for inst_set in current_set)
        self.files.sort_values(inplace=True, ignore_index=True)

        vrp = self.files.tolist()
        
        if self.has_solution:
            self.instances = {f"{int(i/2)}": vrplib.read_instance(vrp[i+1]) for i in range(0, len(vrp), 2)}
            self.solutions = {f"{int(i/2)}": vrplib.read_solution(vrp[i]) for i in range(0, len(vrp), 2)}
        else:
            self.instances = {f"{int(i)}": vrplib.read_instance(vrp[i]) for i in range(0, len(vrp))}

        self.keys = list(self.instances.keys())
        random.shuffle(self.keys)

        


    def next_instance (self, method=None):
        """
        Get next random instance from generator.

        If reset == True, reshuffle instances and restart execution.

        If has_solution == True, return tuple (instance, solution), else return instance

        :param method: Normalization method used at instance generation. If None, return instance unaltered.

        :return (Instance, Solution): Each one as a dict generated by vrplib.
        :return None: If reset == False and generator already returned all instances.
        """

        self.idx += 1
        if self.idx < len(self.keys):
            instance = self.instances[self.keys[self.idx]]
            #print(self.keys[self.idx])
            if instance["dimension"] > self.bounds[1]:
                return self.next_instance(method)
            
            instance["edge_weight"] = self.__normalize_instance(instance, method)

            if instance["edge_weight"].any() == None:
                return self.next_instance(method)
            
            if self.has_solution:
                solution = self.solutions[self.keys[self.idx]]

                return instance, solution
            
            return instance
    
        
        elif self.reset:
            random.shuffle(self.keys)
            self.idx = -1
            return self.next_instance(method)

        return StopIteration

    
    def __normalize_instance (self, instance, method):
        if method == None:
            return instance["edge_weight"]
        
        elif method == "laplacian":
            return self.__laplacian_normalization(instance)
        
        elif method == "symmetric":
            return self.__symmetric_normalization(instance)
        
        elif method == "test":
            return self.__test_normalization(instance)
        
    
    def __laplacian_normalization (self, instance):
        adj_matrix = np.array(instance["edge_weight"])
        deg_matrix = np.diag(np.sum(adj_matrix, axis=1))
        print("D", deg_matrix)
        print("A", adj_matrix)

        L = deg_matrix - adj_matrix
        print("L", L)

        D_sqrt = np.where(deg_matrix > 0, 1/np.sqrt(deg_matrix), 0)
        print(D_sqrt)

        return D_sqrt @ L @ D_sqrt
    

    def __symmetric_normalization (self, instance):
        adj_matrix = np.array(instance["edge_weight"])
        deg_matrix = np.diag(np.sum(adj_matrix, axis=1))

        D_sqrt = np.where(deg_matrix > 0, 1/np.sqrt(deg_matrix), 0)

        return D_sqrt @ adj_matrix @ D_sqrt
    

    def __test_normalization (self, instance):
        adj_matrix = np.array(instance["edge_weight"])
        deg_matrix = np.diag(np.sum(adj_matrix, axis=1))
        #print("D", deg_matrix)
        #print("A", adj_matrix)

        L = deg_matrix - adj_matrix
        #print("L", L)

        D_sqrt = np.where(deg_matrix > 0, 1/np.sqrt(deg_matrix), 0)
        #print(D_sqrt)

        return np.eye(instance["dimension"]) - (D_sqrt @ L @ D_sqrt)
    

# gen = Instance_generator("test_set")
# inst, sol = gen.next_instance("symmetric")

# print(inst["edge_weight"])