import vrplib
import os
import pandas as pd
import random

class Instance_generator ():
    """
    Given a directory with n subsets, generate an iterator that gives the next random .vrp instance from any subset.
    
    Directory structure must be:
        Main Directory -> Set directory -> Instances or Instances and Solutions

    :param directory: The main directory.
    :param bounds: A two tuple with the inferior and superior instance sizes permitted, respectively.
    :param reset: If true, resets the generator with all the instances when finished.
    :param solution: If true, every subset has a .vrp with an equivalent .sol.
    """
    def __init__(self, directory, bounds=(0,101), reset=False, solution=True):
        self.dir = directory
        self.bounds = bounds
        self.instance_sets = os.listdir(directory)
        self.idx = -1
        self.reset = reset

        current_set = [os.path.join(self.dir, inst_set) for inst_set in self.instance_sets]

        self.files = pd.concat(pd.Series(os.path.join(inst_set, inst) for inst in os.listdir(inst_set)) for inst_set in current_set)
        self.files.sort_values(inplace=True, ignore_index=True)

        vrp = self.files.tolist()
        
        self.instances = {f"{int(i/2)}": vrplib.read_instance(vrp[i+1]) for i in range(0, len(vrp), 2)}
        self.solutions = {f"{int(i/2)}": vrplib.read_solution(vrp[i]) for i in range(0, len(vrp), 2)}

        #print(len(self.instances))
        #print(self.instances)
        #print(self.instances)
        self.keys = list(self.instances.keys())
        random.shuffle(self.keys)
        print(self.keys)
        print(self.instances[self.keys[0]])
        print(self.solutions[self.keys[0]])


    def next_instance (self):
        """
        Get next random instance from generator.

        If reset == True, reshuffle instances and restart execution.

        :return (Instance, Solution): Each one as a dict generated by vrplib.
        :return None: If reset == False and generator already returned all instances.
        """

        self.idx += 1
        if self.idx < len(self.keys):
            instance = self.instances[self.keys[self.idx]]
            solution = self.solution[self.keys[self.idx]]

            return instance, solution
        
        elif self.reset:
            random.shuffle(self.keys)
            self.idx = -1
            return self.next_instance()

        return None

    

generator = Instance_generator("test_set")